print("\n********************* calculeter*********************\n")
a=input("enter the firt number =")
b=input("enter the secount number =")
print("the add is ",int(a) + int(b))
print("the sub is ",int(a) - int(b))
print("the mul is ",int(a) * int(b))
print("the div is ",int(a) / int(b))